Coupon notification & channel visibility bulk update
woocommerce/google-listings-and-ads pull request #1105
Opened 2021-11-22 07:02 UTC by chennyxie

### Changes proposed in this Pull Request:

1. add note for coupon upload feature
2. add bulk edit option for coupon channel visibility 

### Screenshots:

![image](https://user-images.githubusercontent.com/87394744/142817488-ea68ff2b-8fa7-4b42-8ca7-0cee962ab345.png)
![image](https://user-images.githubusercontent.com/87394744/142817535-dd5b022b-7703-49dd-80f6-b0ce62281cb0.png)

### Detailed test instructions:
1. Go to coupons page
2. Select several coupons, including a coupon that does not shown on Google
3. Select "bulk actions"->"edit", click apply
4. Default Google visibility equals to "no-change"
5. Select visibility  = show on Google and apply the change
6. verify selected coupon has visibility updated and coupon is sent to Google or pending for sync.

### Changelog entry

>

2021-11-23 22:28 UTC, jconroy commented
Hey @chennyxie just assigned you as the owner and requested a review from @woocommerce/ventures

2021-11-29 18:11 UTC, layoutd commented
Hi @chennyxie, I've done some quick tests and wanted to check whether the bulk edit works for multiple coupons for you:
- Connect to Merchant Center
- Create 3 coupons and set them all to `Show coupon on Google`
- From the Coupons list, select all the coupons and then Bulk Actions > Edit > Apply.
- Set the Google visibility to `Don't show coupon` and then click Update.

For me, only the _first_ coupon has been updating correctly. Could you double-check that? I'll continue my review in the meantime (and try to locate the issue as well).

2021-11-30 13:14 UTC, layoutd requested changes
Hi @chennyxie, this looks good and, with a few tweaks, works in testing. There are a few breaking issues:
- There's a typo in the action name in `BulkEditInitializer` that limits the bulk action to 1 coupon
- There's a dependency in `SetupCouponSharing` that isn't injected correctly, which breaks the note.

Besides that, I've made a few other suggestions for clarification and consistency.

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInitializer.php
> +		add_action( 'save_post_{$', [ $this, 'bulk_edit_hook' ], 10, 2 );
This looks like the reason for the issue where bulk editing [wasn't actually working](https://github.com/woocommerce/google-listings-and-ads/pull/1105#issuecomment-981887769).
```suggestion
		add_action( 'save_post', [ $this, 'bulk_edit_hook' ], 10, 2 );
```

2021-11-30 13:14 UTC, layoutd commented on src/Internal/DependencyManagement/CoreServiceProvider.php
> +use Automattic\WooCommerce\GoogleListingsAndAds\Notes\SetupCouponSharing as SetupCouponSharing;
For all other notes, the word `Note` is appended to the alias to clarify the class purpose, so it would be preferable to have `as SetupCouponSharingNote`, and to use `SetupCouponSharingNote` elsewhere.
```suggestion
use Automattic\WooCommerce\GoogleListingsAndAds\Notes\SetupCouponSharing as SetupCouponSharingNote;
```

2021-11-30 13:14 UTC, layoutd commented on src/Internal/DependencyManagement/CoreServiceProvider.php
> +		SetupCouponSharing::class     => true,
Preferable to use `SetupCouponSharingNote` (will require assignment alignment fix as well).
```suggestion
		SetupCouponSharingNote::class     => true,
```

Also, I've added a related note in `MerchantCenterAwareTrait` about injected `MerchantStatuses` directly.

2021-11-30 13:14 UTC, layoutd commented on src/Internal/DependencyManagement/CoreServiceProvider.php
> +		$this->share_with_tags( SetupCouponSharing::class );
Preferable to use `SetupCouponSharingNote`
```suggestion
		$this->share_with_tags( SetupCouponSharingNote::class );
```

2021-11-30 13:14 UTC, layoutd commented on src/Internal/DependencyManagement/CoreServiceProvider.php
> +		$this->conditionally_share_with_tags( BulkEditInitializer::class );
Neither of these implement the `Conditional` class, so they can use `share_with_tags`
```suggestion
		$this->share_with_tags( CouponBulkEdit::class, CouponMetaHandler::class, MerchantCenterService::class );
		$this->share_with_tags( BulkEditInitializer::class );
```

2021-11-30 13:14 UTC, layoutd commented on src/MerchantCenter/MerchantCenterAwareTrait.php
> +	}
This needs to be [inflected in `CoreServiceProvider`](https://github.com/woocommerce/google-listings-and-ads/blob/4b2276435e0914cd0e2e3e64e043e6bc7ec4b37c/src/Internal/DependencyManagement/CoreServiceProvider.php#L203-L205) in order to work:
```
     ->invokeMethod( 'set_merchant_statuses_object', [ MerchantStatuses::class ] );
```


However, since this isn't really needed in other `MerchantCenterAware` classes, it seems like it would be better to
- Create a `MerchantStatusAwareInterface` and `MerchantStatusAwareTrait`, and use inflection, or (even better)
- Inject the MerchantStatus class directly into the note:
    `CoreServiceProvider`:
    ```php
    $this->share_with_tags( SetupCouponSharing::class, MerchantStatuses::class );
    ```
    `SetupCouponSharing`:
    ```php
	/** @var MerchantStatuses */
	protected $merchant_statuses;

	/**
	 * SetupCouponSharing constructor.
	 *
	 * @param MerchantStatuses $merchant_statuses
	 */
	public function __construct( MerchantStatuses $merchant_statuses ) {
		$this->merchant_statuses = $merchant_statuses;
	}
	````

2021-11-30 13:14 UTC, layoutd commented on src/Notes/SetupCouponSharing.php
> +	public function should_be_added(): bool {
It would be nice to have some explanation of the requirements to show this note, either in the docblock or inline:
- Store is in supported country
- Store has at least one active product in Merchant Center
- Store has coupons created, but no coupons synced with Merchant Center.
- Store has Ads account connected and has been setup for >3 days OR no Ads account and >17 days

Does that look right?

2021-11-30 13:14 UTC, layoutd commented on src/MerchantCenter/MerchantCenterAwareInterface.php
> +	public function set_merchant_statuses_object( MerchantStatuses $merchant_statuses ): void;
Related comment in `MerchantCenterAwareTrait` about injecting `MerchantStatuses` directly into this specific note.

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInitializer.php
> +	public function bulk_edit_hook( int $post_id, $post ) {
```suggestion
	public function bulk_edit_hook( int $post_id, $post ): void {
```

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInterface.php
> +	public function render_view( $column_name, $post_type );
```suggestion
	public function render_view( string $column_name, string $post_type );
```

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInterface.php
> +	 * @return $post_id
```suggestion
	 * @return int $post_id
```

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInterface.php
> +	 * @param object $post Post object being saved.
Could this be `WP_Post`?
https://developer.wordpress.org/reference/hooks/save_post/

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/BulkEditInitializer.php
> +	 * @param object $post Post object being saved.
Could this be `WP_Post`?
https://developer.wordpress.org/reference/hooks/save_post/

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +use Automattic\WooCommerce\GoogleListingsAndAds\Admin\Admin;
Unused import
```suggestion

```

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +	 * @throws ViewException If the view doesn't exist or can't be loaded.
Never thrown.

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +	 * @return $post_id
```suggestion
	 * @return int $post_id
```

2021-11-30 13:14 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +	protected function request_data() {
```suggestion
	protected function request_data(): array {
```

2021-12-08 11:24 UTC, garymurray commented
@j111q can you take a look here - I don't think it looks great having the double button and dismiss link. Ideally there should be one main CTA (a button) and the dismiss text link.

2021-12-10 02:55 UTC, j111q commented
Here's the proposed change to the inbox notification. 
I wasn't sure if we can or can't link to a "Learn more" link within the body copy - let me know if it's not possible. 

@chennyxie, I don't have Alex's github handle - I'll email him directly, and perhaps you can also ping him to get his 👍 

![image](https://user-images.githubusercontent.com/65582817/145509277-f1a4e876-ffcc-4350-a430-104581d608b6.png)

2021-12-11 08:07 UTC, layoutd requested changes
Working well! I added a few more minor changes, and then it will be ready to merge 🥳

2021-12-11 08:07 UTC, layoutd commented on src/Notes/SetupCouponSharing.php
> +				'Sync your store promotions and coupons directly with Google to showcase on your product listings across the Google Shopping tab. When creating a coupon, you’ll see a Channel Visibility settings
I think adding `<br/><br/>` before "When creating a coupon..." will achieve the spacing indicated in @j111q's [comment](https://github.com/woocommerce/google-listings-and-ads/pull/1105#issuecomment-990562495). Currently, the text is all together in one massive paragraph:
![image](https://user-images.githubusercontent.com/228780/145669134-c36151ef-0bee-48ba-bdb1-e415db78f46b.png)

2021-12-11 08:07 UTC, layoutd commented on src/Notes/SetupCouponSharing.php
> +		);
This should be changed from two buttons to the [one "Go to coupons" button](https://github.com/woocommerce/google-listings-and-ads/pull/1105#issuecomment-990562495):
![image](https://user-images.githubusercontent.com/228780/145669134-c36151ef-0bee-48ba-bdb1-e415db78f46b.png)

```suggestion
		$note->add_action(
			'coupon-views',
			__( 'Go to coupons', 'google-listings-and-ads' ),
			$this->get_coupons_url()
		);
```

2021-12-11 08:07 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +		if ( self::get_screen() !== $post_type || self::TARGET_COLUMN !== $column_name ) {
`self::get_screen()` looks like it should be `$this->get_screen()`

2021-12-11 08:07 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +		if ( wp_is_post_revision( $post_id ) || wp_is_post_autosave( $post_id ) || self::get_screen() !== $post->post_type || ! current_user_can( 'edit_post', $post_id ) ) {
`self::get_screen()` looks like it should be `$this->get_screen()`

2021-12-11 08:07 UTC, layoutd commented on src/Admin/BulkEdit/CouponBulkEdit.php
> +use Automattic\WooCommerce\GoogleListingsAndAds\View\ViewException;
Unused import

2021-12-14 18:44 UTC, chennyxie commented
Hi, @layoutd , thanks for your comments I have resolved them then commit the new update. Could you please review again? Thanks in advance

2021-12-15 16:51 UTC, layoutd approved these changes
LGTM! 🚢

2021-12-16 17:35 UTC, merged