Hide Tax UI during onboarding & keep in edit campaign
woocommerce/google-listings-and-ads pull request #2542
Opened 2024-08-19 07:54 UTC by dsawardekar

### Changes proposed in this Pull Request:

Closes https://github.com/woocommerce/google-listings-and-ads/issues/2490

This PR removes the tax rates UI during the onboarding steps. The UI is preserved for the edit campaign flow.

Note: This PR depends on the work in https://github.com/woocommerce/google-listings-and-ads/pull/2543/files. 

### Screenshots:

Onboarding:
![image](https://github.com/user-attachments/assets/28ac8b0e-fc7f-4402-9a58-6e0ca408dbb2)

Edit Campaign:
![image](https://github.com/user-attachments/assets/8908aa17-b327-4fb0-9f39-c67fb9551519)

### Detailed test instructions:

Dependency:
Merge https://github.com/woocommerce/google-listings-and-ads/pull/2543/files into your local branch before testing this feature. Without this you will not be able to continue to Step 3.

1. Start the onboarding steps from a clean slate.
2. You should not see any Tax Rate section
3. You should be able to complete Step 2 and proceed by clicking the Continue button
4. After onboarding, edit the free Campaign 
5. You should see the Tax Rate UI that was removed during onboarding

### Additional details:

Update - Hides tax rate UI during onboarding

### Changelog entry

> Update - Hides the tax rate setting during onboarding.

2024-08-21 19:19 UTC, joemcgill requested changes
I've left one suggestion inline. Otherwise, the main thing that needs to be addressed is that I see an E2E test that's failing related to the validation logic that happens in the `SetupFreeListings` component:

https://github.com/woocommerce/google-listings-and-ads/blob/7acafdf4dbe3c6fa0edd778a483d5a68ac32464d/js/src/components/free-listings/setup-free-listings/index.js#L104-L114

The `checkErrors()` function includes this logic to validate the `tax_rate` value for 'US' based stores:

https://github.com/woocommerce/google-listings-and-ads/blob/7acafdf4dbe3c6fa0edd778a483d5a68ac32464d/js/src/components/free-listings/configure-product-listings/checkErrors.js#L109-L120

We're setting this default for tax rates via the API in #2491, so we need to update this so that the validation for `tax_rates` only runs if `hideTaxRates` is `false`.

2024-08-21 19:19 UTC, joemcgill commented on js/src/edit-free-campaign/index.js
> +				hideTaxRates={ false }
Since this is using the default, this prop can be omitted.
```suggestion
```

2024-08-23 06:14 UTC, dsawardekar commented
@joemcgill I've addressed the PR feedback, can you take another look? thx

2024-08-26 07:07 UTC, ankitrox approved these changes
LGTM 💯

2024-08-26 20:31 UTC, joemcgill approved these changes
I traced down the E2E test failure that I was seeing since I couldn't reproduce it anymore now that [57ecc5d](https://github.com/woocommerce/google-listings-and-ads/pull/2542/commits/57ecc5dbb81d42403ab01113325aad25b2babb04) got merged into this branch. Turns out the default settings get mocked in these tests and needed to be updated in [here](https://github.com/woocommerce/google-listings-and-ads/pull/2542/commits/c2c324212806bdd0d35003c37a2fd651c57efa46).

I went ahead and cleaned up a few more test methods that are no longer used after these changes—something to keep an eye going forward when deleting tests.

2024-08-28 09:26 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.1
* Theme active on store: Storefront Version: 4.6.0
* WooCommerce - Version 9.2.3 
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.6

</Details>



**Test Results -**

- **Positive Test:**

    - The tax selection UI does not appear during onboarding but does appear on the edit campaign screen. ✅
    - The tax selection UI appears when the audience location is set to the US. ✅

- **Negative Test:** The tax selection UI should not appear when the audience location is set to a country outside the US. ✅

- **Default Selection of Tax UI:** "My store uses destination-based tax rates." in the edit campaign screen. ✅ 


**Functional Demo /  Screencast -**

https://github.com/user-attachments/assets/d7b20ff3-4e75-4231-8ccd-21317500bbe7




**Plugin file with this PR related code to test** [google-listings-and-ads.zip](https://github.com/user-attachments/files/16781259/google-listings-and-ads.zip)

2024-08-28 09:26 UTC, ankitguptaindia approved these changes

2024-09-03 10:38 UTC, eason9487 reviewed
Thanks for the change! It works well.

Could you help with removing an unused method?

https://github.com/woocommerce/google-listings-and-ads/blob/4870093d73814c38c835c9498017dda2f2494849/tests/e2e/utils/pages/setup-mc/step-2-product-listings.js#L138-L148

2024-09-03 10:38 UTC, eason9487 commented on js/src/components/free-listings/setup-free-listings/form-content.js
> +	hideTaxRates = false,
The default value of `hideTaxRates` could be removed as the `SetupFreeListings` component already set it and this component is considered as a sub-component of `SetupFreeListings`.

2024-09-03 10:38 UTC, eason9487 commented on js/src/components/free-listings/setup-free-listings/index.js
> + * @param {boolean} [props.hideTaxRates] Whether to hide tax rate section, to be forwarded to `FormContent`.
It would be better to declare the default value as well.

2024-09-05 12:48 UTC, joemcgill commented
@eason9487 I think this is ready for a second review.

2024-09-06 03:59 UTC, eason9487 approved these changes
Thanks for the update!

Although there are JSDoc and code conflict need to be adjusted, I believe it should not need another round of code reviews after resolving them.

2024-09-06 03:59 UTC, eason9487 commented on js/src/components/free-listings/setup-free-listings/form-content.js
> + * @param {boolean} [props.hideTaxRates=false] Whether to hide tax rate section.
This JSDoc needs to be updated as well.

```suggestion
 * @param {boolean} props.hideTaxRates Whether to hide tax rate section.
```

2024-09-11 05:25 UTC, dsawardekar commented
@joemcgill I have updated the jsdoc and fixed the merge conflict. Assigning to you to take another look.

2024-09-11 11:34 UTC, asvinb commented
Change LGTM @dsawardekar . As per @eason9487 's comment, I'am reassigning the ticket to @fblascogarma for UAT.

2024-09-16 16:26 UTC, joemcgill commented
Since this has been approved, I'm merging into the feature branch.

2024-09-16 16:26 UTC, merged