Improve post-onboarding: Show promotion for Google Ads campaign on the Dashboard page
woocommerce/google-listings-and-ads pull request #2650
Opened 2024-10-22 15:10 UTC by kt-12

### Changes proposed in this Pull Request:

Closes #2538.

_Replace this with a good description of your changes & reasoning._

### Screenshots:

<img width="517" alt="image" src="https://github.com/user-attachments/assets/37240a05-6da3-41c9-ad89-de4435d9af9c">

### Detailed test instructions:

1. Complete onboarding by skipping creating a campaign.
2. Go to the dashboard after the MC step. The content should be shown under the Google Ads summary section.
3. Click on the Create Campaign and see if that takes you to the Create Campaign section.
4. Create a campaign, and the section should disappear.

In this task, we have also deprecated the `useFreeAdCredit()`  check the last point in IB. 
Test clicking `Add Paid Campaign`, `Spend $500 to get $500` should only be shown if there is no campaign.

### Additional details:

We have used the common FreeAdCredit component here, which standardises the text and various links associated with that component.

### Changelog entry

> Add - Show promotion for Google Ads campaign on the Dashboard page.

2024-10-25 01:04 UTC, joemcgill requested changes
Nice work! I've left a couple suggestions.

Additionally, I noticed that the heights of each card do not match the designs:

<img width="1172" alt="Screenshot 2024-10-24 at 7 52 47 PM" src="https://github.com/user-attachments/assets/b42c15a7-da8e-43c1-af9d-b1992a7d1590">

I think this will get the right effect:

```diff
diff --git a/js/src/dashboard/index.scss b/js/src/dashboard/index.scss
index c1dfa3b54..417e5efb8 100644
--- a/js/src/dashboard/index.scss
+++ b/js/src/dashboard/index.scss
@@ -26,6 +26,7 @@
 		margin-bottom: var(--main-gap);
 
 		@include break-medium {
+			align-items: flex-start;
 			flex-direction: row;
 		}
 
```

I also noticed that if you create a campaign and then delete it, the promo is no longer being shown. That's because the logic to display the promo relies on the `adsSetupComplete` global in [this line](https://github.com/woocommerce/google-listings-and-ads/blob/5c627985745c41f116f226c4b4ea2cf41e96baa8/js/src/dashboard/summary-section/index.js#L109), which causes this to have the same limitations as the `useAdsCampaign` hook that is being discussed in [this conversation](https://github.com/woocommerce/google-listings-and-ads/pull/2641#pullrequestreview-2391119155), so we may want to update this as well depending on how that conversation is resolved.

2024-10-25 01:04 UTC, joemcgill commented on js/src/components/paid-ads/ads-campaign/paid-ads-features-section.js
> -						{ hasFreeAdCredit && <FreeAdCredit /> }
👍🏻

2024-10-25 01:04 UTC, joemcgill commented on js/src/dashboard/summary-section/paid-features/index.js
> +			<FreeAdCredit />
Using the `FreeAdCredit` component here doesn't quite match the Figma designs:

**Current:**
<img width="587" alt="image" src="https://github.com/user-attachments/assets/157f965e-f333-4b48-8fe8-5b840ddd0117">

**Designs:**
<img width="628" alt="image" src="https://github.com/user-attachments/assets/a60bfd55-1705-4b04-a005-0934b06584b2">

I think it would be best to create a new component in this directory that more closely matches the design. It's important that the "terms and conditions apply" text links to the same URL as the text in the `FreeAdCredit` component.

2024-10-25 01:04 UTC, joemcgill commented on js/src/components/paid-ads/ads-campaign/paid-ads-features-section.js
> -import useFreeAdCredit from '.~/hooks/useFreeAdCredit';
Now that no components are using this hook, the whole file can be deleted.

2024-10-28 13:25 UTC, kt-12 commented on js/src/dashboard/summary-section/paid-features/index.js
> +			<FreeAdCredit />
Fixed.

2024-10-28 13:25 UTC, kt-12 commented on js/src/components/paid-ads/ads-campaign/paid-ads-features-section.js
> -import useFreeAdCredit from '.~/hooks/useFreeAdCredit';
Removed.

2024-10-28 16:41 UTC, joemcgill approved these changes
This looks better to me. Thanks!

2024-10-28 19:06 UTC, ankitguptaindia commented
**QA Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.6.2
* Theme active on store: Twenty Twenty-Four Version: 1.2
* WooCommerce - Version 9.3.3
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 130
* OS: macOS Sonoma 14.6.1 

</Details>


**Test Results:** Implementation works as expected. Google Ads content appears in the Google Ads section on the dashboard when the Ad account doesn’t have any paid campaigns. The "Create Campaign" button redirects to the campaign creation flow. If the user creates a paid campaign, this new content section does not appear. ✅ 



**Functional Demo /  Screencast -**  


https://github.com/user-attachments/assets/60530d9b-4f84-472d-985f-7d7f44813a16

2024-10-28 19:11 UTC, ankitguptaindia commented
@kt-12 @joemcgill  During testing, I noticed that when a merchant creates a new paid campaign, the new section disappears from the Google Ads screen. However, if the merchant deletes the paid campaign and there are no active paid campaigns, this screen content doesn’t reappear. Is this the expected behaviour?

![image](https://github.com/user-attachments/assets/1dc46ee4-c1d5-45c4-ab02-d0a844bf1de3)

2024-10-28 19:27 UTC, kt-12 commented
> @kt-12 @joemcgill During testing, I noticed that when a merchant creates a new paid campaign, the new section disappears from the Google Ads screen. However, if the merchant deletes the paid campaign and there are no active paid campaigns, this screen content doesn’t reappear. Is this the expected behaviour?
> 
> ![image](https://private-user-images.githubusercontent.com/6384299/380857149-1dc46ee4-c1d5-45c4-ab02-d0a844bf1de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNDM3NDYsIm5iZiI6MTczMDE0MzQ0NiwicGF0aCI6Ii82Mzg0Mjk5LzM4MDg1NzE0OS0xZGM0NmVlNC1jMWQ1LTQ1YzQtYWIwMi1kMGE4NDRiZjFkZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTkyNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRhYTRlZDBkMjYzOGRjZGE2NDI0ZjllNjE3NmVjZDY4ZWI4NWQ0MTk0YjA0ZDNhMTgxYjM3ZDgzZjhmMTkwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q0xLK3zIfyaINJK7lYMH3tBZw6yq1tc5MT5ejYs7ULQ)

@ankitguptaindia This is due to a [known issue](https://github.com/woocommerce/google-listings-and-ads/pull/2242#issuecomment-2026060492),  and currently the expected behaviour, too. cc: @joemcgill

2024-10-28 19:28 UTC, joemcgill commented
Great question @ankitguptaindia! Sine the promotion is meant to encourage someone to create their first campaign, I believe this is the expected behavior.

2024-10-30 11:42 UTC, eason9487 requested changes
The first **Acceptance Criteria**:

> When the connected Ads account does not have any existing campaigns, display the Paid Ads features with a CTA to create a campaign.

Currently, the promotion is only displayed before completing the Ads Setup flow. Excluding the considerations mentioned in https://github.com/woocommerce/google-listings-and-ads/pull/2641#issuecomment-2438579282 regarding the existence of a connected account and `adsSetupComplete`, it still doesn't meet this requirement.

> > [...] However, if the merchant deletes the paid campaign and there are no active paid campaigns, this screen content doesn’t reappear. Is this the expected behaviour?

> [...] This is due to a [known issue](https://github.com/woocommerce/google-listings-and-ads/pull/2242#issuecomment-2026060492), and currently the expected behaviour, too.

I would like to emphasize again that the "issue" recognized in that comment is imprecise, and referencing it as a "known issue" is questionable. It's a flag defined by this plugin for identifying if the merchant has completed the Ads Setup flow.

The existing logic using it for determination is because those requirements are based on that definition. If a requirement couldn't be satisfied by its definition, it should not be misplaced as a "known issue" as a reason for not being able to implement the requirement.

2024-10-30 11:42 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/free-ad-credit.js
> +								context="setup-ads"
```suggestion
								context="dashboard"
```

2024-10-30 11:42 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/free-ad-credit.js
> + *
```suggestion
 *
 * @fires gla_documentation_link_click with `{ context: 'dashboard', link_id: 'free-ad-credit-terms', href: 'https://www.google.com/ads/coupons/terms/' }`
```

2024-10-30 11:42 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.js
> + * @return {Card} Card with title and content.
It doesn't appear to return a `Card` and a title.

Furthermore, considering that:

- there is a  `Section` component in this codebase
- there is a `<section>` in HTML elements
- these component names don't include a string of "section"
- these components are not wrapped by `Section` nor `<section>`

Maybe it would be better to avoid using "section" across all codes within the components under the `js/src/dashboard/summary-section/paid-features` directory.

2024-10-30 11:42 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/free-ad-credit.js
> +		<div className="gla-free-ad-credit">
Due to code splitting when building frontend assets, it's not stable to apply CSS belonging to another component. It would be better to have CSS styling in `./index.scss` for this component.

2024-10-30 11:42 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +		margin: $grid-unit-30 0 $grid-unit-20;
Does it need to set `margin`?

2024-10-30 11:42 UTC, eason9487 commented on tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
Suggest adding these tests in a way similar to #2641 and placing them in the `tests/e2e/utils/pages/dashboard.js` rather than this file.

2024-10-30 11:42 UTC, eason9487 commented on tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
Suggest adding these tests in a way similar to #2641 and placing them in the `tests/e2e/utils/pages/dashboard.js` rather than this file.

2024-10-30 11:56 UTC, kt-12 commented
> The first **Acceptance Criteria**:
> 
> > When the connected Ads account does not have any existing campaigns, display the Paid Ads features with a CTA to create a campaign.
> 
> Currently, the promotion is only displayed before completing the Ads Setup flow. Excluding the considerations mentioned in [#2641 (comment)](https://github.com/woocommerce/google-listings-and-ads/pull/2641#issuecomment-2438579282) regarding the existence of a connected account and `adsSetupComplete`, it still doesn't meet this requirement.
> 
> > > [...] However, if the merchant deletes the paid campaign and there are no active paid campaigns, this screen content doesn’t reappear. Is this the expected behaviour?
> 
> > [...] This is due to a [known issue](https://github.com/woocommerce/google-listings-and-ads/pull/2242#issuecomment-2026060492), and currently the expected behaviour, too.
> 
> I would like to emphasize again that the "issue" recognized in that comment is imprecise, and referencing it as a "known issue" is questionable. It's a flag defined by this plugin for identifying if the merchant has completed the Ads Setup flow.
> 
> The existing logic using it for determination is because those requirements are based on that definition. If a requirement couldn't be satisfied by its definition, it should not be misplaced as a "known issue" as a reason for not being able to implement the requirement.

I agree here that this is definitely within the boundaries of what was defined. Calling it a "known issue" issue would be wrong; all I wanted to point to @ankitguptaindia is that this behaviour is `known` to us and is well within the limit of definition.

2024-11-01 01:33 UTC, kt-12 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +		margin: $grid-unit-30 0 $grid-unit-20;
It only amounts to a minimal visual change. Without margin, it felt slightly better, so I removed it.

2024-11-01 01:38 UTC, kt-12 commented on js/src/dashboard/summary-section/paid-features/free-ad-credit.js
> +		<div className="gla-free-ad-credit">
Move those styles within  `./index.scss`.

2024-11-01 02:54 UTC, kt-12 commented on js/src/dashboard/summary-section/paid-features/index.js
> + * @return {Card} Card with title and content.
Updated. As most elements were div, I replaced `section` with `div` at most places.

2024-11-01 02:54 UTC, kt-12 commented on tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
Moved to `tests/e2e/specs/dashboard/paid-features.test.js`

2024-11-01 11:26 UTC, eason9487 requested changes
The issue of not meeting the first acceptance criteria mentioned in https://github.com/woocommerce/google-listings-and-ads/pull/2650#pullrequestreview-2403990521 remains unresolved.

- If it's confirmed that the acceptance criteria is correct, then the current implementation will still need adjustments since the promotion is not shown after all campaigns are removed.
- If it's confirmed that the current implementation meets the actual requirement, then that acceptance criteria should be corrected to align with the requirement.

If a PR was merged while leaving the implementation didn't meet with the acceptance criteria, this would make it very confusing for people in the future when tracing back the development history of the codebase.

2024-11-01 11:26 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +			fill: #5ec862;
I just realized that there is design document during this round.

![image](https://github.com/user-attachments/assets/19e36fed-64d1-43b3-a4f5-629bebba269b)

There are some details that are different from the design document:

- Text color
- Icon color, size, and alignment

2024-11-01 11:26 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.js
> + * @return {Card} Card with title and content.
Having `div` in the naming is also not necessary as `<div>` is very generic and may be presented in a variety of forms. It's only helpful to include something in the naming if it has a more specific or attributable presentation.

Therefore, there's no need to mention "div" in JSDoc or have div` in naming for this case.

2024-11-01 11:26 UTC, eason9487 commented on tests/e2e/utils/pages/dashboard.js
> +		);
Related to https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1822151992

2024-11-01 11:26 UTC, eason9487 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +		await expect( dashboardPage.paidFeaturesDiv ).toContainText(
Related to https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1822151992

2024-11-05 02:12 UTC, joemcgill reviewed
This looks very close. Left a couple suggestions, otherwise, once the Jest tests are sorted, this is working as expected.

2024-11-05 02:12 UTC, joemcgill commented on js/src/dashboard/summary-section/index.js
> +	}
Since we reverted the change to useAdsCampaigns() and no longer need to check for the `adsSetupComplete` status, this can be further simplified to simply check for the length of `adsCampaignsData` (returning `null` until the campaign data is loaded is a good idea!)

```suggestion
	if ( ! loaded ) {
		return null;
	}

	const showCampaignPromotionCard = Boolean( ! adsCampaignsData?.length );
```

2024-11-05 02:12 UTC, joemcgill commented on tests/e2e/specs/dashboard/paid-features.test.js
> +		test( 'When atleast one campaign present', async () => {
Typo:

```suggestion
		test( 'When at least one campaign present', async () => {
```

2024-11-05 02:12 UTC, joemcgill commented on js/src/dashboard/summary-section/paid-features/index.scss
> +		color: #1e1e1e;
Prefer project variables:

```suggestion
		padding: $grid-unit-20 $grid-unit-15;
		color: $gray-900;
```

2024-11-05 15:06 UTC, joemcgill approved these changes

2024-11-06 06:36 UTC, eason9487 commented on js/src/dashboard/summary-section/index.js
> +	const showCampaignPromotionCard = Boolean( ! adsCampaignsData?.length );
The `!` operator already does the boolean typecasting. The second time boolean typecasting `Boolean()` is redundant.

2024-11-06 06:36 UTC, eason9487 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +		await expect( dashboardPage.paidFeaturesDiv ).toContainText(
There is still a `div`.

https://github.com/woocommerce/google-listings-and-ads/blob/9caf01d1c6e63142acc3de96e2e112de2e76442a/tests/e2e/specs/dashboard/paid-features.test.js#L54

2024-11-06 08:08 UTC, eason9487 requested changes

2024-11-06 08:08 UTC, eason9487 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +		test( 'When no campaign present', async () => {
Avoiding API errors or adding another test for no campaigns in the API response would be better.

![image](https://github.com/user-attachments/assets/5604ada6-4330-4c4f-803d-d463e874b328)

2024-11-06 08:08 UTC, eason9487 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +			await expect( dashboardPage.paidFeatures ).not.toBeVisible();
This assertion can also pass while it's in loading state, and then it ends with an API error.

![image](https://github.com/user-attachments/assets/1f62b0e0-64be-42d9-b9e2-c5bc5e80cdf4)

![image](https://github.com/user-attachments/assets/052e7cb4-2846-4e11-82ff-48e9c54a3965)

It would be more robust to assert what's on the screen after data are loaded.

![image](https://github.com/user-attachments/assets/848aad93-9097-4c82-a054-ab283c3290a9)

2024-11-06 08:08 UTC, eason9487 commented on js/src/dashboard/summary-section/summary-section.test.js
> +	} );
The current cases test other targets on the premise that there are campaigns. However, this `mockCampaigns` function and the `mockCampaigns( [] );`  calls in test cases make the overall look misleading. Because the call of `mockCampaigns( [] );` mocks a return value of `{ loaded: true, data: [ [] ] }`, which doesn't match the actual shape of `useAdsCampaigns`.

https://github.com/woocommerce/google-listings-and-ads/blob/9caf01d1c6e63142acc3de96e2e112de2e76442a/js/src/hooks/useAdsCampaigns.js#L15-L22

https://github.com/woocommerce/google-listings-and-ads/blob/9caf01d1c6e63142acc3de96e2e112de2e76442a/js/src/data/actions.js#L42-L60

It's recommended to:

- Remove `mockCampaigns( [] );` calls from test cases, and simply and directly mock the return value in the `beforeAll` block. For example:
   ```js
   beforeAll( () => {
   	useAdsCampaigns.mockReturnValue( {
   		// ... omitted
   	} );
   } );
   ```
- Correct the mocked return value to  at least the type of `Array<Campaign>` is correct, e.g. `{ returned: true, data: [ {} ] }`.

2024-11-06 08:08 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +			fill: #5ec862;
Continue on https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1825669577.

Screenshot from the current implementation:

![1](https://github.com/user-attachments/assets/0e94bb68-74ab-4b85-a7d8-3fb7424692eb)

Screenshots from the design document:

![2](https://github.com/user-attachments/assets/ebc9e124-1659-490a-bce3-1ae5129827ff)
![3](https://github.com/user-attachments/assets/381ae60a-1ff6-4b23-8915-fe86a8db7181)

There are still some details that are different:

- Icon color (should be `$gla-color-green`)
- Icon size
- Icon alignment

2024-11-06 08:08 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +		font-size: $gla-font-base;
This font size can be omitted as the font size inherited from the parent is the same.

2024-11-07 00:36 UTC, joemcgill commented
@eason9487 I believe everything is addressed here. I've made a few additional style tweaks to get closer to the Figma designs, but as you've noted, this was designed with a different icon set than what the plugin is currently using. I've tried to match as best as possible.

2024-11-07 03:06 UTC, eason9487 reviewed
Hi @joemcgill

Thanks for the style adjustments!

> I believe everything is addressed here.

The https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1830477423 and https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1830486425 are not resolved.

2024-11-07 03:06 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/free-ad-credit.js
> +			<GridiconGift size={ 16 } />
```suggestion
			<GridiconGift />
```

2024-11-07 03:06 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +			flex: 0 0 auto;
```suggestion
			fill: $alert-green;
```

2024-11-07 03:06 UTC, eason9487 commented on js/src/dashboard/summary-section/paid-features/index.scss
> +			margin: $grid-unit-10 / 2;
```suggestion
```

2024-11-07 03:33 UTC, kt-12 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +			await expect( dashboardPage.paidFeatures ).not.toBeVisible();
Done. Introduced a new fulfill to handle the api.

2024-11-07 03:34 UTC, kt-12 commented on tests/e2e/specs/dashboard/paid-features.test.js
> +		test( 'When no campaign present', async () => {
Mocked no campaign blank array here.

2024-11-07 03:40 UTC, kt-12 commented
> Hi @joemcgill
> 
> Thanks for the style adjustments!
> 
> > I believe everything is addressed here.
> 
> The [#2650 (comment)](https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1830477423) and [#2650 (comment)](https://github.com/woocommerce/google-listings-and-ads/pull/2650#discussion_r1830486425) are not resolved.

Hi @eason9487, 

I have pushed e2e changes, which will address the remaining review comments.

2024-11-07 03:57 UTC, eason9487 approved these changes
Thanks for the work. LGTM.

2024-11-07 13:03 UTC, merged