Return 401 when retrieving status data
woocommerce/google-listings-and-ads pull request #857
Opened 2021-07-05 11:42 UTC by mikkamp

### Changes proposed in this Pull Request:

This PR specifically checks if the Google Account is not connected when we retrieve the status data. This error returns a 401 error which triggers the UI to enter the reconnect flow.

Closes #847 

### Detailed test instructions:

1. Set the Google Account as disconnected by setting the option `gla_google_connected` to 0 in the `wp_options` table
2. Clear the status transient from the Connection test page
3. Send a request to `GET /wc/gla/mc/product-statistics`
4. Confirm we get a 401 response with the message "Google Account is not connected."

### Changelog entry
* Tweak - 401 error when retrieving status data and Google account is not connected.

2021-07-06 16:33 UTC, layoutd requested changes
This works as described for the Product Statistics and Product Feed endpoints, but breaks in the `IssuesController` endpoint because `get_issues` (which calls `maybe_refresh_status_data`) isn't in a `try-catch`:
https://github.com/woocommerce/google-listings-and-ads/blob/819f77f1fc1ae8fdbfbbb2075a54f5fff580f5eb/src/API/Site/Controllers/MerchantCenter/IssuesController.php#L81-L83

Currently, it's not a _huge_ issue because a product statistics is generally always sent before the merchant issues and product feeds requests, _but_ it's possible for a merchant to load the Product Feed page, wait for the cache to expire, then try to navigate the "Issues to resolve" table, which would make an "orphan" paginated request to the issues endpoint, and get this error.

- To test: clear MC status cache and make a `GET` request to `/wp-json/wc/gla/mc/issues`. Should get an unhandled exception.
- To fix: add a try catch like in [`ProductFeedController`](https://github.com/woocommerce/google-listings-and-ads/blob/4b10d2f6edb6ec545ec6a78975f8c7f961f700e2/src/API/Site/Controllers/MerchantCenter/ProductFeedController.php#L69-L71)

2021-07-07 06:17 UTC, mikkamp commented
Nice catch. I thought it would have been safe because the docblock already indicated it could throw an exception. But I'll fix that up so it catches those exceptions as needed.

2021-07-07 08:12 UTC, layoutd commented
> I thought it would have been safe because the docblock already indicated it could throw an exception. 

Pretty embarrassing for [whoever made that change](https://github.com/woocommerce/google-listings-and-ads/blame/819f77f1fc1ae8fdbfbbb2075a54f5fff580f5eb/src/API/Site/Controllers/MerchantCenter/IssuesController.php#L81-L83) … 🙃

2021-07-07 08:47 UTC, mikkamp commented
Added a try and catch block in b4fb774 and a few small fixes in the comments/docblocks
Ready for another review.

2021-07-07 09:35 UTC, layoutd approved these changes
Looks good works for all endpoints now 👍🏻 

Last little nitpick: 
- https://github.com/woocommerce/google-listings-and-ads/blob/989e6856c66ee4ded79d9fff08bb9e0dd5fa9b01/src/MerchantCenter/MerchantStatuses.php#L170-L175
Should the wording of the second exception be changed to match the first (i.e., `Merchant Center account is not connected`)? Or maybe `is not configured` or `is not set up`?

2021-07-07 10:10 UTC, merged